#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
import sys

GPIO.setmode(GPIO.BCM)
GPIO.setup(12, GPIO.OUT)
GPIO.setwarnings(False)

angle = int(sys.argv[1])
duty = float(angle) / 10 + 5

pwm = GPIO.PWM(12,100)
pwm.start(5)

pwm.ChangeDutyCycle(duty)
time.sleep(0.5)

GPIO.cleanup()
